spring.datasource.url=${BOOKING_PROD_DB_URL}
spring.datasource.username=${BOOKING_PROD_DB_USERNAME}
spring.datasource.password=${BOOKING_PROD_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
