spring.datasource.url=${SUPPORT_PROD_DB_URL}
spring.datasource.username=${SUPPORT_PROD_DB_USERNAME}
spring.datasource.password=${SUPPORT_PROD_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
