spring.application.name=support-chat-service
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/itemlist
spring.datasource.username=postgres
spring.datasource.password=Chandu@2628
spring.datasource.driver-class-name=org.postgresql.Driver

//spring.jpa.hibernate.ddl-auto=none
//spring.jpa.show-sql=true

jwt.secret=THIS_IS_A_LONG_RANDOM_SECRET_KEY_MIN_32_CHARS
jwt.access-token-minutes=120
carwash.security.enabled=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chandupremgunda@gmail.com
spring.mail.password=gllpdtblsteozrfx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=chandupremgunda@gmail.com