spring.datasource.url=${INVITATION_PROD_DB_URL}
spring.datasource.username=${INVITATION_PROD_DB_USERNAME}
spring.datasource.password=${INVITATION_PROD_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
