spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: chandupremgunda@gmail.com
    password: ukgfgozznxgkgrpn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    from: chandupremgunda@gmail.com

# Optional: Add these if running as standalone
server:
  port: 8089

logging:
  level:
    com.carwash.mailnotification: DEBUG