spring:
  config:
    import: optional:file:../env.properties
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    from: ${MAIL_FROM}

# Optional: Add these if running as standalone
server:
  port: 8089

logging:
  level:
    com.carwash.mailnotification: DEBUG

---
# =============================================
# QA profile — port 9089
# =============================================
spring:
  config:
    activate:
      on-profile: qa

server:
  port: 9089

---
# =============================================
# Prod profile — port 10089
# =============================================
spring:
  config:
    activate:
      on-profile: prod

server:
  port: 10089