spring.datasource.url=${PAYMENT_PROD_DB_URL}
spring.datasource.username=${PAYMENT_PROD_DB_USERNAME}
spring.datasource.password=${PAYMENT_PROD_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
