#spring.application.name=payment-service
#server.port=8083
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/itemlist
#spring.datasource.username=postgres
#spring.datasource.password=Chandu@2628
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.application.name=payment-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/itemlist
spring.datasource.username=postgres
spring.datasource.password=Chandu@2628
spring.datasource.driver-class-name=org.postgresql.Driver

//spring.jpa.hibernate.ddl-auto=none
//spring.jpa.show-sql=true

jwt.secret=THIS_IS_A_LONG_RANDOM_SECRET_KEY_MIN_32_CHARS
jwt.access-token-minutes=120

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# ==================== PhonePe PG config ====================

phonepe.environment=UAT
phonepe.base.url=https://api-preprod.phonepe.com/apis/pg-sandbox

# IMPORTANT: keep this starting with DUMMY so dev shortcut triggers
phonepe.merchant.id=DUMMY_MERCHANT_ID
phonepe.salt.key=DUMMY_SALT_KEY
phonepe.salt.index=1

phonepe.callback.url=http://localhost:8083/payments/phonepe/callback

phonepe.client.id=DUMMY_CLIENT_ID
phonepe.client.secret=DUMMY_CLIENT_SECRET
