spring.datasource.url=${MEMBERSHIP_PROD_DB_URL}
spring.datasource.username=${MEMBERSHIP_PROD_DB_USERNAME}
spring.datasource.password=${MEMBERSHIP_PROD_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
