spring.application.name=membership
server.address=0.0.0.0
server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/itemlist
spring.datasource.username=postgres
spring.datasource.password=Chandu@2628
spring.datasource.driver-class-name=org.postgresql.Driver

//spring.jpa.hibernate.ddl-auto=none
//spring.jpa.show-sql=true



spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=THIS_IS_A_LONG_RANDOM_SECRET_KEY_MIN_32_CHARS
jwt.access-token-minutes=120
carwash.security.enabled=true
