server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/itemlist
    username: postgres
    password: Chandu@2628
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: 12345678901234567890123456789012
    expiration-ms: 86400000